//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_IS
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookReview
    {
        public long ID_Review { get; set; }
        public long ID_Book { get; set; }
        public string UserName { get; set; }
        public string ReviewText { get; set; }
        public System.DateTime Date_Time { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
    }
}
